---
# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    image: registry.gitlab.com/chrisna.mitt/fruitlegum:latest
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
